# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

#  -*- coding: utf-8 -*-
x = 1
y = 2
f = 0
fsum = 2
print(x)
print(y)
while f < 4000000:
    f = x + y
    x = y
    y = f
    if f % 2 == 0:
        fsum = fsum + f
        print(fsum)

